version: '3'

services:
  # Frontend
  web:
    image: jitsi/web:stable
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - /config/web:/config
      - /config/transcripts:/usr/share/jitsi-meet/transcripts
    labels:
      service: "jitsi-web"
    environment:
      - PUBLIC_URL=https://docker-jitsi-meet-production.up.railway.app
      - ENABLE_XMPP_WEBSOCKET=1
      - ENABLE_HTTP_REDIRECT=1
      - ENABLE_RECORDING=1
      - XMPP_BOSH_URL_BASE=https://docker-jitsi-meet-production.up.railway.app/http-bind
    networks:
      - meet.jitsi
    depends_on:
      - prosody
      - jicofo
      - jvb

  # XMPP server
  prosody:
    image: jitsi/prosody:stable
    restart: ${RESTART_POLICY:-unless-stopped}
    expose:
      - '5269'
      - '5347'
      - '5280'
    volumes:
      - /config/prosody:/config
    environment:
      - PUBLIC_URL=https://docker-jitsi-meet-production.up.railway.app
    networks:
      - meet.jitsi

  # Jicofo
  jicofo:
    image: jitsi/jicofo:stable
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - prosody
    environment:
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - PUBLIC_URL=https://docker-jitsi-meet-production.up.railway.app
    networks:
      - meet.jitsi

  # Video Bridge (JVB)
  jvb:
    image: jitsi/jvb:stable
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '10000:10000/udp'
    environment:
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - ENABLE_COLIBRI_WEBSOCKET=1
      - PUBLIC_URL=https://docker-jitsi-meet-production.up.railway.app
    depends_on:
      - prosody
    networks:
      - meet.jitsi

networks:
  meet.jitsi:
